FROM fedora:28

RUN dnf -y install \
  --setopt=deltarpm=0 \
  --setopt=install_weak_deps=false \
  --setopt=tsflags=nodocs \
  nmap-ncat \
  python3-devel \
  python3-dockerfile-parse \
  python3-flake8 \
  python3-koji \
  python3-mock \
  'python3-neomodel >= 3.3.0' \
  python3-pytest \
  python3-pytest-cov \
  && dnf clean all

RUN pip3 install flake8-docstrings
VOLUME /src
WORKDIR /src
# Inspired from https://github.com/neo4j-contrib/neomodel/blob/master/tests-with-docker-compose.sh
CMD ["sh", "-c", "while ! nc -z -w 2 neo4j 7687; do sleep 1; done; pytest-3 -vvv --cov-report term-missing --cov=assayist tests/ && flake8"]
