FROM fedora:28

RUN dnf -y install \
  --setopt=deltarpm=0 \
  --setopt=install_weak_deps=false \
  --setopt=tsflags=nodocs \
  nmap-ncat \
  python3-devel \
  python3-dockerfile-parse \
  python3-flake8 \
  python3-koji \
  python3-mock \
  python3-pytest \
  python3-pytest-cov \
  && dnf clean all

# We require at least neomodel 3.2.9 to get the bugfix in dd42548e4a3d484fd1265be834893f1212be680d.
# Fedora currently only has rpms for 3.2.8. Let's install 3.3.0 from koji directly.
RUN dnf -y install https://kojipkgs.fedoraproject.org//packages/python-neomodel/3.3.0/1.fc28/noarch/python3-neomodel-3.3.0-1.fc28.noarch.rpm

RUN pip3 install flake8-docstrings
VOLUME /src
WORKDIR /src
# Inspired from https://github.com/neo4j-contrib/neomodel/blob/master/tests-with-docker-compose.sh
CMD ["sh", "-c", "while ! nc -z -w 2 neo4j 7687; do sleep 1; done; pytest-3 -vvv --cov-report term-missing --cov=assayist tests/ && flake8"]
